### ISSUE TITLE
java.lang.IllegalArgumentException: URI scheme is not "file"

### ISSUE THREAD

**Issue by vra5107** [jannon/jsdoc3-ant-task#6]
Hi I am seeing this error for some reason. Not sure what is going on. 

Here are my ant lines ..

```
  <taskdef name="jsdoc" classname="net.jannon.ant.tasks.JsDoc3" classpath="${jsdoc3-task-jar}:${rhino-jar}"/>


 <target name="docs">
     <jsdoc jsdochome="C:/Users/vakkive/jsdoc-3.1.1/" to="build/doc/" file="./js/bundles.js" recurse="true"/>
 </target>
```

Here is the stack trace.

 [jsdoc] java.lang.IllegalArgumentException: URI scheme is not "file"
    [jsdoc]     at java.io.File.<init>(File.java:366)
    [jsdoc]     at org.jsdoc.JsDocModuleProvider.loadFromUri(JsDocModuleProvider.java:36)
    [jsdoc]     at org.mozilla.javascript.commonjs.module.provider.UrlModuleSourceProvider.loadFromPathList(UrlModuleSourceProvider.java:108)
    [jsdoc]     at org.mozilla.javascript.commonjs.module.provider.UrlModuleSourceProvider.loadFromPrivilegedLocations(UrlModuleSourceProvider.java:89)
    [jsdoc]     at org.mozilla.javascript.commonjs.module.provider.ModuleSourceProviderBase.loadSource(ModuleSourceProviderBase.java:37)
    [jsdoc]     at org.mozilla.javascript.commonjs.module.provider.CachingModuleScriptProviderBase.getModuleScript(CachingModuleScriptProviderBase.java:65)
    [jsdoc]     at org.mozilla.javascript.commonjs.module.provider.SoftCachingModuleScriptProvider.getModuleScript(SoftCachingModuleScriptProvider.java:63)
    [jsdoc]     at org.mozilla.javascript.commonjs.module.Require.getModule(Require.java:359)
    [jsdoc]     at org.mozilla.javascript.commonjs.module.Require.getExportedModuleInterface(Require.java:260)
    [jsdoc]     at org.mozilla.javascript.commonjs.module.Require.call(Require.java:214)
    [jsdoc]     at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
    [jsdoc]     at org.mozilla.javascript.gen.C__Users_vakkive_jsdoc_3_1_1__jsdoc_js_1._c_anonymous_1(Unknown Source)
    [jsdoc]     at org.mozilla.javascript.gen.C__Users_vakkive_jsdoc_3_1_1__jsdoc_js_1.call(Unknown Source)
    [jsdoc]     at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
    [jsdoc]     at org.mozilla.javascript.gen.C__Users_vakkive_jsdoc_3_1_1__jsdoc_js_1._c_script_0(Unknown Source)
    [jsdoc]     at org.mozilla.javascript.gen.C__Users_vakkive_jsdoc_3_1_1__jsdoc_js_1.call(Unknown Source)
    [jsdoc]     at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:426)
    [jsdoc]     at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3178)
    [jsdoc]     at org.mozilla.javascript.gen.C__Users_vakkive_jsdoc_3_1_1__jsdoc_js_1.call(Unknown Source)
    [jsdoc]     at org.mozilla.javascript.gen.C__Users_vakkive_jsdoc_3_1_1__jsdoc_js_1.exec(Unknown Source)
    [jsdoc]     at org.mozilla.javascript.tools.shell.Main.evaluateScript(Main.java:654)
    [jsdoc]     at org.mozilla.javascript.tools.shell.Main.processFileSecure(Main.java:552)
    [jsdoc]     at org.mozilla.javascript.tools.shell.Main.processFile(Main.java:507)
    [jsdoc]     at org.mozilla.javascript.tools.shell.Main.processSource(Main.java:499)
    [jsdoc]     at org.mozilla.javascript.tools.shell.Main.processFiles(Main.java:215)
    [jsdoc]     at org.mozilla.javascript.tools.shell.Main$IProxy.run(Main.java:134)
    [jsdoc]     at org.mozilla.javascript.Context.call(Context.java:521)
    [jsdoc]     at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:535)
    [jsdoc]     at org.mozilla.javascript.tools.shell.Main.exec(Main.java:198)
    [jsdoc]     at org.mozilla.javascript.tools.shell.Main.main(Main.java:174)
    [jsdoc]     at net.jannon.ant.tasks.JsDoc3.execute(Unknown Source)
    [jsdoc]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
    [jsdoc]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [jsdoc]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    [jsdoc]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    [jsdoc]     at java.lang.reflect.Method.invoke(Method.java:597)
    [jsdoc]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    [jsdoc]     at org.apache.tools.ant.Task.perform(Task.java:348)
    [jsdoc]     at org.apache.tools.ant.Target.execute(Target.java:392)
    [jsdoc]     at org.apache.tools.ant.Target.performTasks(Target.java:413)
    [jsdoc]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
    [jsdoc]     at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
    [jsdoc]     at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    [jsdoc]     at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
    [jsdoc]     at org.apache.tools.ant.Main.runBuild(Main.java:811)
    [jsdoc]     at org.apache.tools.ant.Main.startAnt(Main.java:217)
    [jsdoc]     at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
    [jsdoc]     at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

**Comment by jannon** [comment]
Hey, the lines of your ant file did not make it in the post above.

**Comment by vra5107** [comment]
try now.
